#!/bin/bash
# Cross-build Qt6 (qtbase Core only) for NXP MIMXRT1170-EVKB (Cortex-M7).
# Companion to build-qt-host-x11sim.sh; this is the embedded variant.
#
# Approach: build qtbase as STATIC archives using the Zephyr SDK
# arm-zephyr-eabi toolchain.  The resulting libs are linked into a
# Zephyr application by west build (a thin wrapper CMakeLists is
# expected to find_package(Zephyr) and find_package(Qt6) against the
# install prefix).
#
# Caveats / known wrinkles, in case this fails:
# - Qt's architecture_test (qtbase/cmake/QtBaseConfigureTests.cmake)
#   try_compiles an executable in *project mode*, so
#   CMAKE_TRY_COMPILE_TARGET_TYPE=STATIC_LIBRARY does not help.  The
#   Zephyr SDK's newlib leaves _sbrk / _write / _close etc. unresolved
#   when linking standalone; we pass --unresolved-symbols=ignore-all to
#   make the link succeed.  The resulting binary doesn't run, but
#   file(STRINGS) only needs to grep "==Qt=magic=Qt==" out of it.
# - qtbase/src/corelib/kernel/qeventdispatcher_zephyr.cpp includes
#   <zephyr/kernel.h>.  We add ${ZEPHYR_BASE}/include to the include path
#   to satisfy that, but CONFIG_* macros normally come from Zephyr's
#   generated autoconf.h.  Expect this file to need separate handling.

set -e

PREFIX="${PREFIX:-${HOME}/qt-zephyr-rt1170}"
QT_SOURCE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BUILD_DIR="${BUILD_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/build-qt-zephyr-rt1170}"
ZEPHYR_SDK_INSTALL_DIR="${ZEPHYR_SDK_INSTALL_DIR:-${HOME}/org/zephyrproject/zephyr-sdk-1.0.1}"
ZEPHYR_BASE="${ZEPHYR_BASE:-${HOME}/org/zephyrproject/zephyrproject/zephyr}"
QT_HOST_PATH="${QT_HOST_PATH:-${HOME}/qt-x11-sim}"

GREEN='\033[0;32m'; RED='\033[0;31m'; NC='\033[0m'
info()  { echo -e "${GREEN}Info:${NC} $*"; }
error() { echo -e "${RED}Error:${NC} $*" >&2; exit 1; }

[ -d "$QT_SOURCE_DIR" ] || error "Qt source not found at $QT_SOURCE_DIR"
# SDK 1.0.x moved toolchains under <SDK>/gnu/<arch>/.  Fall back to the
# pre-1.0 layout if someone points at an older SDK.
if [ -d "$ZEPHYR_SDK_INSTALL_DIR/gnu/arm-zephyr-eabi" ]; then
    TOOLCHAIN_ROOT="$ZEPHYR_SDK_INSTALL_DIR/gnu/arm-zephyr-eabi"
elif [ -d "$ZEPHYR_SDK_INSTALL_DIR/arm-zephyr-eabi" ]; then
    TOOLCHAIN_ROOT="$ZEPHYR_SDK_INSTALL_DIR/arm-zephyr-eabi"
else
    error "Zephyr SDK ARM toolchain not found under $ZEPHYR_SDK_INSTALL_DIR (checked gnu/arm-zephyr-eabi and arm-zephyr-eabi)"
fi
[ -d "$ZEPHYR_BASE/include/zephyr" ] \
    || error "Zephyr source headers not found under $ZEPHYR_BASE/include/zephyr"
[ -d "$QT_HOST_PATH" ] || error "QT_HOST_PATH (host Qt6 tools) not found at $QT_HOST_PATH"

mkdir -p "$BUILD_DIR"

info "Configuring Qt6 cross-build for RT1170 (Cortex-M7)..."
info "  source:      $QT_SOURCE_DIR"
info "  build:       $BUILD_DIR"
info "  prefix:      $PREFIX"
info "  Zephyr SDK:  $ZEPHYR_SDK_INSTALL_DIR"
info "  ZEPHYR_BASE: $ZEPHYR_BASE"
info "  QT_HOST_PATH:$QT_HOST_PATH"

cat > "$BUILD_DIR/zephyr-rt1170-toolchain.cmake" <<EOF
# CMake toolchain file for Qt6 cross-build targeting MIMXRT1170-EVKB
# (NXP iMX RT1170, Cortex-M7).  Generated by build-qt-zephyr-rt1170.sh.

set(CMAKE_SYSTEM_NAME Zephyr)
set(CMAKE_SYSTEM_PROCESSOR arm)
set(CMAKE_SYSTEM_VERSION 1)

set(TOOLCHAIN_BIN "$TOOLCHAIN_ROOT/bin")
set(CMAKE_C_COMPILER   \${TOOLCHAIN_BIN}/arm-zephyr-eabi-gcc)
set(CMAKE_CXX_COMPILER \${TOOLCHAIN_BIN}/arm-zephyr-eabi-g++)
set(CMAKE_ASM_COMPILER \${TOOLCHAIN_BIN}/arm-zephyr-eabi-gcc)
set(CMAKE_AR           \${TOOLCHAIN_BIN}/arm-zephyr-eabi-ar)
set(CMAKE_RANLIB       \${TOOLCHAIN_BIN}/arm-zephyr-eabi-ranlib)
set(CMAKE_NM           \${TOOLCHAIN_BIN}/arm-zephyr-eabi-nm)
set(CMAKE_OBJDUMP      \${TOOLCHAIN_BIN}/arm-zephyr-eabi-objdump)
set(CMAKE_OBJCOPY      \${TOOLCHAIN_BIN}/arm-zephyr-eabi-objcopy)

# RT1170 Cortex-M7 + double-precision FPU (fpv5-d16).
# -fno-short-enums: the ARM EABI default is -fshort-enums (see the
# __ARM_SIZEOF_MINIMAL_ENUM=1 predef in arm-zephyr-eabi-gcc), but Qt's
# static_assert(sizeof(QCborValue::Type) == sizeof(QJsonValue::Type))
# fails under short-enums (one is 1-byte, the other 4-byte).  Qt code
# doesn't share enums across the Qt/Zephyr API boundary in a way that
# would create an ABI mismatch, so flipping this is safe for our build.
set(CPU_FLAGS "-mcpu=cortex-m7 -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -fno-short-enums")

# Static libraries for a bare-metal MCU target must NOT be PIC.  CMake's
# default Qt build emits -fPIC for libraries; Zephyr links the final ELF
# with -fno-pic -fno-pie, which leaves any PIC relocations from Stage 1
# unresolvable against the linker's discarded crtbegin.o .got.plt
# section.  Force position-DEPENDENT code globally.
set(CMAKE_POSITION_INDEPENDENT_CODE OFF)
add_compile_options(-fno-pic -fno-pie)
add_link_options(-fno-pic -fno-pie)
# Note: dropped -ffreestanding.  Zephyr apps have a real libc + heap so
# they are hosted, not freestanding.  gcc 14's libstdc++ guards every
# hosted-only header (qsimd.cpp pulls in <bits/requires_hosted.h>) with
# `#error "This header is not available in freestanding mode."`

# gcc 14 (Zephyr SDK 1.0.1) promotes several K&R-era warnings to errors
# by default.  Bundled 3rd-party C (PCRE2, zlib) trips on these.  Demote
# back to warnings for the cross build.
add_compile_options(
    -Wno-error=incompatible-pointer-types
    -Wno-error=implicit-function-declaration
    -Wno-error=implicit-int
    -Wno-error=int-conversion
)
# qharfbuzzng.cpp:512 assigns hb_codepoint_t* (unsigned long*) to glyph_t*
# (unsigned int*).  Both are 32-bit on ARM-M but the C++ type checker
# doesn't know that.  -fpermissive demotes the strict conversion error to
# a warning -- the assignment is binary-safe at this CPU width.
add_compile_options($<$<COMPILE_LANGUAGE:CXX>:-fpermissive>)

# Define __ZEPHYR__ so qtbase/src/corelib/global/qsystemdetection.h
# picks the Q_OS_ZEPHYR branch we patched in.  Stage 1 deliberately does
# NOT include <zephyr/*> headers (that comes in Stage 2 inside west build),
# so we don't need CONFIG_* macros or stub generated headers.
add_compile_definitions(
    __ZEPHYR__=1
    # newlib gates clock_gettime/clock_settime/clock_getres etc. on
    # _POSIX_TIMERS.  Without this the symbols are not declared and Qt's
    # qdatetime.cpp fails to compile.  Stage 1 only needs the declarations
    # to satisfy the type checker -- bodies will be linked in Stage 2 by
    # Zephyr's POSIX subsystem.
    _POSIX_TIMERS=1
    # Expose POSIX 2008 + BSD-derived legacy APIs (putenv lives here, as
    # do other functions Qt corelib reaches for unconditionally).
    _POSIX_C_SOURCE=200809L
    _DEFAULT_SOURCE=1
    # HarfBuzz: arm-zephyr-eabi libstdc++ doesn't expose std::mutex
    # (single-threaded build), and we have no pthread.  HB_NO_MT
    # switches its mutex impl to a no-op stub (typedef int).
    HB_NO_MT
)

# Stage 1 POSIX shim headers for the handful of <sys/*> headers that Qt
# corelib unconditionally pulls in but newlib/picolibc on bare-metal ARM
# does not provide (sys/utsname.h, sys/mman.h).  Placed BEFORE the SDK's
# system include path so the shims take precedence for these specific
# headers without affecting any other <sys/*> resolution.
include_directories(BEFORE SYSTEM "$QT_SOURCE_DIR/qtbase/mkspecs/zephyr-arm-cm7-g++/stage1-shim")
set(CMAKE_C_FLAGS_INIT   "\${CPU_FLAGS}")
set(CMAKE_CXX_FLAGS_INIT "\${CPU_FLAGS}")
set(CMAKE_ASM_FLAGS_INIT "\${CPU_FLAGS}")

# try_compile() default target: static lib avoids link-time unresolved
# symbol failures for simple per-feature checks.
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

# QtBaseConfigureTests.cmake builds the architecture_test as an executable
# via try_compile in project mode, which ignores CMAKE_TRY_COMPILE_TARGET_TYPE.
# Allow the link to "succeed" with newlib stubs unresolved; the binary is
# never run, only grepped for the embedded magic-string architecture tag.
set(CMAKE_EXE_LINKER_FLAGS_INIT "-Wl,--unresolved-symbols=ignore-all")

# Tell Qt this is a Zephyr build so qt_set01(ZEPHYR ...) yields 1 and the
# qzephyr plugin subdirectory + corelib's qeventdispatcher_zephyr.cpp are
# added to the build.  ZEPHYR_BASE also gets propagated to the plugin's
# include path (see qtbase/src/plugins/platforms/zephyr/CMakeLists.txt:28).
set(ZEPHYR_BASE "$ZEPHYR_BASE")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

# Bypass architecture autodetect: try_compile cannot run the resulting
# binary on the host, so help Qt understand we are 32-bit big/little.
set(TEST_architecture_arch "arm" CACHE STRING "")
set(TEST_subarch_result "neon" CACHE STRING "")
set(TEST_buildAbi "arm-little_endian-ilp32" CACHE STRING "")
EOF

CMAKE_OPTS=(
    -DCMAKE_INSTALL_PREFIX="$PREFIX"
    -DCMAKE_TOOLCHAIN_FILE="${BUILD_DIR}/zephyr-rt1170-toolchain.cmake"
    -DCMAKE_BUILD_TYPE=Release
    -DBUILD_SHARED_LIBS=OFF
    -DFEATURE_static=ON
    -DQT_HOST_PATH="$QT_HOST_PATH"
    # Stage 1 cross-build uses a Cortex-M7-specific mkspec whose
    # qplatformdefs.h deliberately does NOT include <zephyr/kernel.h>
    # or <zephyr/posix/*>.  Those headers require Zephyr's Kconfig
    # autoconf.h / generated syscall stubs, which only exist inside
    # west build (Stage 2).
    -DQT_QMAKE_TARGET_MKSPEC=zephyr-arm-cm7-g++
    # Defer Zephyr-runtime-aware Qt code (corelib's qeventdispatcher_zephyr
    # and the qzephyr QPA plugin sources) to Stage 2.  See
    # qtbase/src/corelib/CMakeLists.txt:1465 for the condition.
    -DQT_DEFER_ZEPHYR_RUNTIME=ON

    # Tier 6 scope: Core + Gui + Widgets (QApplication + QTabWidget +
    # QPushButton + ... for the Qt-official Widgets Gallery demo).
    -DFEATURE_gui=ON
    -DFEATURE_widgets=ON
    # PrintSupport ships moc-generated code that references a private
    # QPrintDialogPrivate but the corresponding cpp is not compiled in
    # the bare-build configuration -- we don't need printing on an MCU.
    -DFEATURE_printsupport=OFF

    # FreeType: needed for any text rendering on the qzephyr backing
    # store (no system font server on the MCU).  Use the bundled copy
    # that ships inside qtbase rather than the nonexistent system one.
    -DFEATURE_freetype=ON
    -DFEATURE_system_freetype=OFF
    # HarfBuzz: complex-script shaping the gallery / qmlsample examples
    # need on the host build too -- use the bundled fork.
    -DFEATURE_harfbuzz=ON
    -DFEATURE_system_harfbuzz=OFF
    # PNG: bundle for QImage::load() in the demos.  zlib is already
    # bundled by qtbase.
    -DFEATURE_png=ON
    -DFEATURE_system_png=OFF

    # Disable features that need OS/host services we don't have on Zephyr.
    -DFEATURE_concurrent=OFF
    -DFEATURE_dbus=OFF
    -DFEATURE_dlopen=OFF
    -DFEATURE_eventfd=OFF
    -DFEATURE_filesystemwatcher=OFF
    -DFEATURE_fontconfig=OFF
    -DFEATURE_future=OFF
    -DFEATURE_glib=OFF
    -DFEATURE_icu=OFF
    -DFEATURE_jpeg=ON
    -DFEATURE_library=OFF
    -DFEATURE_network=OFF
    -DFEATURE_opengl=OFF
    -DFEATURE_opengles2=OFF
    -DFEATURE_opengles3=OFF
    -DFEATURE_egl=OFF
    -DFEATURE_vulkan=OFF
    # quick_vectorimage compiles SVG resources to QML at build-time via
    # the svgtoqml host tool.  Our host Qt install does not build that
    # tool, and the regular QImage / QSvgRenderer path is enough for
    # demos like coffee that just <Image source="*.svg"/> their assets.
    -DFEATURE_quick_vectorimage=OFF
    # The V4 JS engine's JIT (qtdeclarative/src/3rdparty/masm/) requires
    # mprotect + sysconf(_SC_PAGESIZE), neither of which is available
    # under Zephyr's POSIX subset.  Disable the JIT and run the QML
    # bytecode interpreter only -- plenty fast for embedded UIs.
    -DFEATURE_qml_jit=OFF
    # The QML network loader needs QNetworkAccessManager (qtbase
    # FEATURE_network=OFF for us), so cut it from QML too.  Apps that
    # ship their own qrc:/ resources do not need the network path.
    -DFEATURE_qml_network=OFF
    # INPUT_opengl=no disables Qt's OpenGL auto-detection altogether so
    # no compile test runs and FEATURE_opengl=OFF isn't second-guessed.
    -DINPUT_opengl=no
    -DFEATURE_openssl=OFF
    -DFEATURE_pch=OFF
    -DFEATURE_pkg_config=OFF
    -DFEATURE_process=OFF
    -DFEATURE_processenvironment=OFF
    -DFEATURE_sharedmemory=OFF
    -DFEATURE_sql=OFF
    -DFEATURE_system_doubleconversion=OFF
    -DFEATURE_systemsemaphore=OFF
    -DFEATURE_testlib=OFF
    -DFEATURE_thread=OFF
    -DFEATURE_xml=OFF
    -DFEATURE_zstd=OFF

    # Qt's compile-test feature detection misjudges glibc/Linux-only
    # features because newlib's headers declare the function prototype
    # (gated on _GNU_SOURCE) without providing the implementation.  The
    # compile test passes, FEATURE_xxx is set ON, then the real build
    # references the undefined function.  Explicitly OFF for everything
    # that's GNU-extension / Linux-only and would never link against
    # newlib's bare-metal libc anyway.
    -DFEATURE_dup3=OFF
    -DFEATURE_accept4=OFF
    -DFEATURE_copy_file_range=OFF
    -DFEATURE_futimens=OFF
    -DFEATURE_getauxval=OFF
    -DFEATURE_getentropy=OFF
    -DFEATURE_inotify=OFF
    -DFEATURE_linkat=OFF
    -DFEATURE_memmem=OFF
    -DFEATURE_memrchr=OFF
    -DFEATURE_ppoll=OFF
    -DFEATURE_pollts=OFF
    -DFEATURE_pthread_clockjoin=OFF
    -DFEATURE_pthread_condattr_setclock=OFF
    -DFEATURE_pthread_timedjoin=OFF
    -DFEATURE_cxa_thread_atexit=OFF
    -DFEATURE_cxa_thread_atexit_impl=OFF
    -DFEATURE_dladdr=OFF

    # qtbase: Core + Gui + Widgets statics.
    # qtdeclarative: QtQml + QtQuick + Quick Controls 2.  Includes the
    # software scene-graph adaptation we need (no GPU on RT1170).
    # qtsvg: QSvgPlugin (image format) + the QtSvg module for vector
    # cup/icon resources used by demos like coffee.
    #
    # NOTE: qtshadertools is intentionally NOT included here -- not
    # because it can't compile for Zephyr (the qtshadertools submodule
    # carries a patch that makes glslang's OSdependent build on
    # Zephyr via its Unix backend), but because at runtime the
    # Cortex-M7 firmware never invokes the qsb / shader-pipeline code:
    # we run QtQuick's software scene-graph adaptation, which uses
    # QPainter rather than precompiled .qsb shaders.  qtdeclarative's
    # *build* step does need qsb to pre-compile shaders that get
    # embedded in libQt6Quick.a's QRC, but that runs on the host via
    # QT_HOST_PATH/bin/qsb -- no need to cross-build a Cortex-M7 qsb.
    "-DQT_BUILD_SUBMODULES=qtbase;qtdeclarative;qtsvg"
    # Explicitly force these submodules ON.  An earlier Tier 2 build
    # configured this tree with -DBUILD_qtdeclarative=OFF and the cache
    # still carries it as UNINITIALIZED=OFF, which makes
    # qt5/CMakeLists.txt:71 skip the submodule dependency check.
    -DBUILD_qtdeclarative=ON
    -DBUILD_qtsvg=ON
    # qtshadertools gets auto-pulled by qtdeclarative as a dependency,
    # but its runtime libraries hit std::mutex / lvalue-conversion
    # errors when cross-built without full libstdc++ threads.  Skip the
    # target build -- the only thing qtdeclarative actually needs from
    # qtshadertools is the host `qsb` tool, which lives in QT_HOST_PATH.
    -DBUILD_qtshadertools=OFF
    # Do NOT build target-side host tools (qml runtime, qmlscene, qml-
    # easing, etc.) -- they are huge Qt apps in their own right and the
    # default Cortex-M7 linker script obviously cannot fit a 20+ MB
    # executable into flash.  Stage 2 only consumes the static
    # libQt6Qml.a / libQt6Quick.a archives, not the qml binary.
    -DQT_BUILD_TOOLS_BY_DEFAULT=OFF
    # Cortex-M7 cross-build: the host has SDL2 installed (for the X11
    # sim plugin) but we don't want QZEPHYR_WITH_SDL baked into
    # libqzephyr.a for the embedded target -- otherwise flush()'s
    # non-SDL Zephyr display_write() branch becomes dead code.
    -DZEPHYR_NATIVE_SIM=OFF
    -DQT_BUILD_EXAMPLES=OFF
    -DQT_BUILD_TESTS=OFF
)

info "Running CMake configure..."
cmake -G Ninja -S "$QT_SOURCE_DIR" -B "$BUILD_DIR" "${CMAKE_OPTS[@]}"

info "Building qtbase (Core only)..."
cmake --build "$BUILD_DIR" --parallel "$(nproc)"

info "Installing to $PREFIX..."
cmake --install "$BUILD_DIR"

info "Done.  Qt6 (Cortex-M7 static libs) installed under $PREFIX/lib."
